### PR TITLE
👩🏽‍💻Add follow the mouse cursor

### PR DESCRIPTION
**Pull request by AuTa**
Without setting to toggle.

code from @蚕子

### CODE REVIEW

**Comment by AuTa** [comment]
When use keyboard to select text, miss the menu.

**Comment by AuTa** [comment]
image

The div below is the position of the cursor.

**Comment by AuTa** [comment]
display after mouseup:

```js
      document.addEventListener("selectionchange", function (event) {
        setTimeout(async () => {
          const activeLeaf = app.workspace.getActiveViewOfType(MarkdownView);
          if (activeLeaf) {
            // create event handler
            const popHandler = function (event: Event) {
              cMenu.style.visibility = activeLeaf.editor.somethingSelected() ? "visible" : "hidden";
              // await new Promise((resolve) => { setTimeout(resolve, 200); });
              const selection = window.getSelection();
              // getCientRects returns all the positioning information we need
              const selectionContainer = selection.getRangeAt(0).commonAncestorContainer as HTMLElement;
              const rect = selectionContainer.getClientRects()[0]

              cMenu.style.height = `${cMenu.offsetHeight}px`;
              // TODO: parents are different, position is error.
              cMenu.style.left = `${rect.right - cMenu.offsetWidth * 1.5}px`;
              if (rect.bottom + cMenu.offsetHeight < document.body.clientHeight) {
                cMenu.style.top = `${rect.bottom}px`;
              } else {
                cMenu.style.top = `${rect.top - cMenu.offsetHeight * 1.5}px`;
              }
              // after cancel select
              let timmer = setInterval(() => {
                if (!activeLeaf.editor.somethingSelected()) {
                  cMenu.style.visibility = "hidden";
                  clearInterval(timmer);
                };
              }, 100);

              document.removeEventListener("mouseup", popHandler);
              document.removeEventListener("keyup", popHandler);
            };
            // add mouseup and keyup event listener
            document.addEventListener("mouseup", popHandler);
            document.addEventListener("keyup", popHandler);
          };
        }, 10);
      });
```

**Comment by chetachiezikeuzor** [comment]
> display after mouseup:
> 
> ```js
>       document.addEventListener("selectionchange", function (event) {
>         setTimeout(async () => {
>           const activeLeaf = app.workspace.getActiveViewOfType(MarkdownView);
>           if (activeLeaf) {
>             // create event handler
>             const popHandler = function (event: Event) {
>               cMenu.style.visibility = activeLeaf.editor.somethingSelected() ? "visible" : "hidden";
>               // await new Promise((resolve) => { setTimeout(resolve, 200); });
>               const selection = window.getSelection();
>               // getCientRects returns all the positioning information we need
>               const selectionContainer = selection.getRangeAt(0).commonAncestorContainer as HTMLElement;
>               const rect = selectionContainer.getClientRects()[0]
> 
>               cMenu.style.height = `${cMenu.offsetHeight}px`;
>               // TODO: parents are different, position is error.
>               cMenu.style.left = `${rect.right - cMenu.offsetWidth * 1.5}px`;
>               if (rect.bottom + cMenu.offsetHeight < document.body.clientHeight) {
>                 cMenu.style.top = `${rect.bottom}px`;
>               } else {
>                 cMenu.style.top = `${rect.top - cMenu.offsetHeight * 1.5}px`;
>               }
>               // after cancel select
>               let timmer = setInterval(() => {
>                 if (!activeLeaf.editor.somethingSelected()) {
>                   cMenu.style.visibility = "hidden";
>                   clearInterval(timmer);
>                 };
>               }, 100);
> 
>               document.removeEventListener("mouseup", popHandler);
>               document.removeEventListener("keyup", popHandler);
>             };
>             // add mouseup and keyup event listener
>             document.addEventListener("mouseup", popHandler);
>             document.addEventListener("keyup", popHandler);
>           };
>         }, 10);
>       });
> ```

I think this is very excellent! I was going to say that mouse would be way too costly in appending and removing cMenu form the DOM. But selection change is much better. Thank you for this contribution! I will have to play with this a bit and see that it works wonderfully (I suspect that it will)!

**Review by chetachiezikeuzor — COMMENTED** [review]
Menu escaping window will need to be handled. But it looks good!

**Comment by chetachiezikeuzor** [comment]
Menu needs to be killed when cursor is moved out of note

**Pull request merged**
